version: '3.8'

services:
  soap-api:
    build: .
    container_name: soap-api
    ports:
      - "8000:8000"
    environment:
      - ORACLE_USER=YourUsername
      - ORACLE_PASSWORD=YourPassword
      - ORACLE_DSN=oracle-xe/XE
    networks:
      - oracle-network

networks:
  oracle-network:
    external: true